steps:
- name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- name: 'gcr.io/cloud-builders/go'
  args: ['fmt', './...']
  env: ['PROJECT_ROOT=$REPO_NAME']
- name: 'gcr.io/cloud-builders/go'
  args: ['vet', './...']
  env: ['PROJECT_ROOT=$REPO_NAME']
